image:
  repository: registry.cn-hangzhou.aliyuncs.com/kubernetes-syncer/demoapp
  tag: v1.0.0

# configmap:
#   main:
#     enabled: true
#     data:
#       config.yaml: |
#         date_format: UnixDate

# persistence:
#   config:
#     enabled: true
#     type: configmap
#     objectName: main
#     mountPath: /etc/demoapp
#     readonly: true
#     defaultMode: "0420"
#     targetSelectAll: true
