image:
  repository: registry.cn-hangzhou.aliyuncs.com/kubernetes-syncer/demoapp
  pullPolicy: IfNotPresent
  tag: v1.0.0

service:
  main:
    enabled: true
    primary: true
    ports:
      main:
        enabled: true
        port: 80
        targetPort: 80

# configmap:
#   main:
#     enabled: true
#     data:
#       config.yaml: |
#         date_format: UnixDate

# persistence:
#   config:
#     enabled: true
#     type: configmap
#     objectName: main
#     mountPath: /etc/demoapp
#     readonly: true
#     defaultMode: "0420"
#     targetSelectAll: true
