# -- Docs: https://truecharts.org/general/

# -- Global values
global:
  # -- Set additional global labels
  labels: {}
  # -- Set additional global annotations
  annotations: {}
  fallbackDefaults:
    # -- Default probe type
    probeType: http
    # -- Default Service Protocol
    serviceProtocol: tcp
    # -- Default Service Type
    serviceType: ClusterIP
    # -- Default persistence type
    persistenceType: pvc
    # -- Default probe timeouts
    probeTimeouts:
      liveness:
        initialDelaySeconds: 12
        periodSeconds: 15
        timeoutSeconds: 5
        failureThreshold: 5
        successThreshold: 1
      readiness:
        initialDelaySeconds: 10
        periodSeconds: 12
        timeoutSeconds: 5
        failureThreshold: 4
        successThreshold: 2
      startup:
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 3
        failureThreshold: 60
        successThreshold: 1
  # -- Enable to stop most pods and containers including cnpg
  # does not include stand-alone pods
  stopAll: false

image:
  repository: ilolicon/demoapp
  pullPolicy: IfNotPresent
  tag: v1.0.0

imagePullSecret:
  public-secret:
    enabled: true
    existingSecret: acr-public-credentials

# -- Security Context
securityContext:
  # -- Container security context for all containers
  # Can be overruled per container
  container:
    runAsUser: 568
    runAsGroup: 568
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      add: []
      drop:
      - ALL
      # When set to false, it will automatically
      # add CHOWN, SETUID, SETGID, FOWNER, DAC_OVERRIDE
      # capabilities ONLY when container runs as ROOT
      disableS6Caps: false
    # -- PUID for all containers
    # Can be overruled per container
    PUID: 568
    # -- UMASK for all containers
    # Can be overruled per container
    UMASK: "0022"
  # -- Pod security context for all pods
  # Can be overruled per pod
  pod:
    fsGroup: 568
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups: []
    sysctls: []

# -- Resources
# Can be overruled per container
resources:
  limits:
    cpu: 2000m
    memory: 2000Mi
  requests:
    cpu: 100m
    memory: 250Mi

containerOptions:
  NVIDIA_CAPS:
  - all

# -- Options for all pods
# Can be overruled per pod
podOptions:
  dnsConfig:
    options:
    - name: single-request-reopen
  automountServiceAccountToken: false
  terminationGracePeriodSeconds: 60

workload:
  main:
    enabled: true
    primary: true
    type: Deployment
    podSpec:
      containers:
        main:
          enabled: true
          primary: true
          imageSelector: image
          probes:
            liveness:
              enabled: true
              path: /-/healthy
              type: "{{ .Values.service.main.ports.main.protocol }}"
              port: "{{ $.Values.service.main.ports.main.targetPort | default .Values.service.main.ports.main.port }}"
            readiness:
              enabled: true
              path: /-/ready
              type: "{{ .Values.service.main.ports.main.protocol }}"
              port: "{{ $.Values.service.main.ports.main.targetPort | default .Values.service.main.ports.main.port }}"
            startup:
              enabled: true
              path: /-/ready
              type: "{{ .Values.service.main.ports.main.protocol }}"
              port: "{{ $.Values.service.main.ports.main.targetPort | default .Values.service.main.ports.main.port }}"

# -- Timezone used everywhere applicabl
TZ: Asia/Shanghai

# -- Diagnostic Mode
diagnosticMode:
  enabled: false

# -- Service configuration
service:
  main:
    enabled: true
    primary: true
    ports:
      main:
        enabled: true
        primary: true
        protocol: http
        port: 80
        targetPort: 8080

# configmap:
#   main:
#     enabled: true
#     data:
#       config.yaml: |
#         date_format: UnixDate

# persistence:
#   config:
#     enabled: true
#     type: configmap
#     objectName: main
#     mountPath: /etc/demoapp
#     readonly: true
#     defaultMode: "0420"
#     targetSelectAll: tru

# -- This section contains some pre-config for frequently used dependencies
dependencies:

# -- For disable Helm-Itellisense lint
common:
